name: Build and Generate Binary

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build application
        run: npm run build

      - name: Generate binary
        run: pkg . -o dist/my-svelte-app.exe

      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-svelte-app
          path: dist/my-svelte-app.exe

      - name: Configure AWS credentials
        shell: bash
        run: |
          # Configure AWS CLI
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region 'ap-southeast-1'

          # Extract tag name
          TAG_NAME=$(echo ${GITHUB_REF##*/})
          echo "Extracted tag name: $TAG_NAME"

          # Upload the binary to Amazon S3
          aws s3 cp ./dist/my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/$TAG_NAME/front_end/my-svelte-app --acl public-read
