name: Build and Deploy Svelte App

on:
  push:
    tags:
      - '**'  # Trigger only on tag pushes

jobs:
  build-and-upload:
    runs-on: windows-latest  # Changed to Windows runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Binary
        run: npm run package

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region # e.g., us-east-1

      - name: Upload Binary to S3
        run: aws s3 cp ./my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/${{ github.ref }}/my-svelte-app.exe --acl public-read


      # Optional: Archive the binary as a workflow artifact
      - name: Archive Binary
        uses: actions/upload-artifact@v2
        with:
          name: my-svelte-app
          path: my-svelte-app.exe