name: Build and Deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Svelte project
      run: npm run build

    - name: Generate binary
      run: |
        echo "Generating binary..."
        # Replace the commands below with your actual binary generation steps
        # For example, if you're using webpack:
        # webpack --config webpack.config.js
        # Or if you have a custom script to generate the binary:
        # npm run generate-binary
        # Here's a placeholder command:
        touch dist/svelte_binary/binary.txt

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-1'
        SOURCE_DIR: dist/svelte_binary
        DEST_DIR: svelte_binary
