name: Build and Deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 

    - name: Install Dependencies
      run: npm install

    - name: Build Svelte App
      run: npm run build
      # This builds your Svelte app

    - name: Install pkg
      run: npm install -g pkg

    - name: Generate Binary
      run: pkg . --output dist/svelte-binary.exe
      # This assumes you have a pkg configuration in your package.json or a separate config file

    - name: Run Binary
      run: dist/svelte-binary.exe
      # Replace 'dist/svelte-binary.exe' with the path to your binary file

    - name: Configure AWS credentials and Upload Binary to S3
      run: |
        # Configure AWS CLI
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region 'ap-southeast-1' # Use your AWS region

        # Upload the binary to Amazon S3
        aws s3 cp ./dist/svelte-binary.exe s3://${{ secrets.AWS_BUCKET }}/front_end/svelte-binary --acl public-read
