name: Build and Store Binary to AWS S3

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build binary
        run: npm run build

      - name: Debug - List files in dist directory
        run: dir ./dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-1'

      - name: Debug - List files in S3 bucket
        run: aws s3 ls s3://${{ secrets.AWS_BUCKET }}/refs/heads/master/dist/

      - name: Upload binary to S3
        run: aws s3 cp ./dist/my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/refs/heads/master/dist/my-svelte-app.exe

      - name: Verify binary in S3
        run: aws s3 ls s3://${{ secrets.AWS_BUCKET }}/refs/heads/master/dist/
