name: Build and Deploy

on:
  push:
    tags:
      - '**'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Svelte project
      run: npm run build

    - name: Package application (Windows only)
      run: npm run package

    - name: List output files
      run: ls ./dist

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Upload Windows binary to AWS S3
      run: aws s3 cp ./dist/hrmadminportal-win.exe s3://${{ secrets.AWS_BUCKET }}/hrmadminportal-win.exe --acl public-read
