name: Build and Generate Binary

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure this version is compatible with all dependencies

      - name: Install dependencies
        run: npm install

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build application
        run: npm run build
        # Make sure your build script prepares everything needed for pkg

      - name: Generate binary
        run: pkg . --out-path dist --targets node18-win-x64
        # Specifying the target explicitly helps ensure compatibility

      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-svelte-app
          path: dist/my-svelte-app.exe

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Upload binary to AWS S3
        run: aws s3 cp ./dist/my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/${{ github.ref_name }}/front_end/my-svelte-app.exe --acl public-read
        # Ensure the path and permissions are correctly set
