name: Build and Deploy Svelte App

on:
  push:
    tags:
      - '**'

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Run the job on a Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Match the Node.js version with your project requirements

    - name: Install dependencies
      run: npm install

    - name: Build Svelte project
      run: npm run build

    - name: Package application
      run: npm run package  # This should refer to the "package" script in your package.json

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'  # Specify your AWS region

    - name: Upload binary to AWS S3
      run: aws s3 cp ./dist/my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/my-svelte-app.exe --acl public-read
      # Make sure to replace AWS_BUCKET_NAME with your actual S3 bucket name stored in your repository secrets

