name: Build and Deploy Svelte App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1' # Set Node.js version to 18.17

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Check if node_modules exists
        run: |
          if (Test-Path -Path "node_modules") {
            Remove-Item -Path "node_modules" -Recurse -Force
          }

      - name: Remove package-lock.json
        run: Remove-Item -Path package-lock.json -Force

      - name: Install Dependencies
        run: npm install

      - name: Build Svelte App
        run: npm run build

      - name: Install pkg
        run: npm install -g pkg@5.8.1

      - name: Generate Binary
        run: npm run package

      - name: List Files in Directory
        run: dir /s

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-1' # Use your AWS region

      - name: Upload Binary to S3
        run: |
          aws s3 cp ./my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/${{ github.ref }}/my-svelte-app.exe --acl public-read
