name: Build and Deploy Svelte App

on:
  push:
    tags:
      - '**'  # Trigger only on tag pushes

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Use Node.js version 18

    - name: Install Dependencies
      run: |
        npm install
        npm install -g @vercel/ncc pkg@5.8.1

    - name: Build Svelte App
      run: npm run build

    - name: Bundle Application
      run: ncc build src/main.js -o dist

    - name: Generate Binary
      run: pkg ./dist/main.js --output my-svelte-app.exe --targets node18-win-x64

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-southeast-1' # Use your AWS region

    - name: Upload Binary to S3
      run: |
        aws s3 cp ./my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/${{ github.ref }}/my-svelte-app.exe --acl public-read
