name: Build and Deploy Svelte App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (ensuring Node.js is available)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust as needed

      - name: Install Dependencies
        run: npm install

      - name: Build Svelte App
        run: npm run build

      - name: Package Svelte App (using separate script)
        # Try one of the following options:
        # Option 1: Using full path to `node` (if necessary)
        run: ./node ./scripts/package.cjs  # Adjust path if needed
        # Option 2: Using path added to environment (less recommended)
        # run: echo "::add-path::$(npm prefix -g)/bin" && node ./scripts/package.cjs
        # Option 3: Utilize provided Node.js (may require script adjustments)
        # run: ./scripts/package.cjs

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-1'

      - name: Upload Binary to S3
        run: aws s3 cp ./dist/my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/${{ github.sha }}/my-svelte-app.exe --acl public-read
