name: Build and Deploy Svelte App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18  # Adjust based on project requirements (check Svelte compatibility)
        uses: actions/setup-node@v3
        with:
          node-version: 18  # No change needed here if using Node.js 18

      - name: Install Dependencies
        run: npm ci  # Use npm ci for a clean install during CI

      - name: Build Svelte App
        run: npm run build

      - name: Install pkg
        run: npm install -g pkg

      - name: Package Svelte App
        run: npm run package

      - name: Run Tests (Optional)
        run: npm test  # Add your project's test command here if you have tests

      - name: Verify Binary Execution (Optional)
        # Adjust the path based on your project structure
        run: .\dist\my-svelte-app.exe  # Test the binary execution locally

      - name: Upload Binary to S3 (Optional)  # Conditionally upload based on needs
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-1'
      - name: Upload Binary to S3 (Optional)
        run: aws s3 cp ./dist/my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/${{ github.ref }}/my-svelte-app.exe --acl public-read
