name: Build and Deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Svelte project
      run: npm run build

    - name: Create binary directory
      run: mkdir dist\svelte_binary

    - name: Generate binary
      run: |
        echo "Generating binary..."
        # Replace the commands below with your actual binary generation steps
        # For example, if you're using webpack:
        # webpack --config webpack.config.js
        # Or if you have a custom script to generate the binary:
        # npm run generate-binary
        # Here's a placeholder command:
        echo "Binary content" > dist\svelte_binary\binary.txt

    - name: Upload to S3
      run: aws s3 sync dist\svelte_binary s3://${{ secrets.AWS_BUCKET }}/svelte_binary --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-southeast-1'
