name: Build and Deploy Svelte App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Consider using 'ubuntu-latest' if Windows runner issues persist

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (ensuring Node.js is available)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust as needed

      - name: Check Node.js Installation
        run: node -v

      - name: Install Dependencies
        run: npm install

      - name: Build Svelte App
        run: npm run build

      - name: Grant permissions for execution (if necessary)
        run: chmod +x ./scripts/package.cjs

      - name: Package Svelte App (using separate script)
        run: node ./scripts/package.cjs  # Use `node` directly (recommended)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-1'

      - name: Upload Binary to S3
        run: aws s3 cp ./dist/my-svelte-app.exe s3://${{ secrets.AWS_BUCKET }}/${{ github.sha }}/my-svelte-app.exe --acl public-read
