name: Build and Deploy Svelte App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Svelte App
        run: npm run build

      - name: Install pkg
        run: npm install -g pkg

      - name: Package Svelte App
        run: npm run package

      - name: Confirm Build Output
        run: ls -l ./dist/hrmadminportal.exe

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-1'

      - name: Upload Binary to S3
        run: aws s3 cp ./dist/hrmadminportal.exe s3://${{ secrets.AWS_BUCKET }}/${{ github.sha }}/hrmadminportal.exe --acl public-read
