name: Build and Deploy

on:
  push:
    tags:
      - '**'

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build the project
      run: npm run build
      
    - name: Package the application
      run: npm run package

    - name: List files in the dist directory
      run: ls -l ./dist
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1' 

    - name: Upload binary to AWS S3
      run: aws s3 cp ./dist/hrmadminportal.exe s3://${{ secrets.AWS_BUCKET }}/${{ github.ref_name }}/front_end/hrmadminportal.exe --acl public-read
      
